//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QReal_MobileDesigner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.UserProjects = new HashSet<UserProject>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Package { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<UserProject> UserProjects { get; set; }
    }
}
