// <auto-generated />
namespace QReal_MobileDesigner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class DelProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DelProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201403291547073_DelProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
